---
title: Rosalind
author: 
- |-
  _^1^ Department of Biology, Emory University, 1510 Clifton Road NE, Atlanta, GA, USA, 30322_
  <!-- _^2^ _ -->
  ^['This Supplementary Material can be found at https://github.com/darwinanddavis/rosalind']
#bibliography:/Users/malishev/Documents/Melbourne Uni/Thesis_2016/library.bib
output:
  html_document:
    code_folding: show
    depth: 3
    number_sections: no
    toc: yes
    toc_float: yes
  pdf_document:
    template: null
    toc: yes
  word_document:
    highlight: tango
    keep_md: yes
    pandoc_args: --smart
    #reference: mystyles.docx
    toc: yes
includes:
  before_body: before_body.tex
subtitle: Matthew Malishev^1^*
tags:
- nothing
- nothingness
params: 
  date: !r Sys.Date()
  version: !r getRversion()
  email: "matthew.malishev@gmail.com"
  dir: "/Users/malishev/Documents/Data/Rosalind/Rosalind/"
classoption: portrait
vignette: >
  %\VignetteIndexEntry{Rosalind problem set}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

```{r, echo = FALSE}
knitr::opts_chunk$set(
 eval = TRUE, tidy.opts=list(width.cutoff=60), tidy=TRUE, echo=TRUE, warning = FALSE, message = FALSE
)
```

Date: `r params$date`  
R version: `r params$version`   
*Corresponding author: `r params$email`  

## Overview     
This document contains the code and solutions to the coding problem sets from the Rosalind database at http://rosalind.info/problems/list-view/  

---   
\   

```{r echo = F}
setwd(params$dir) # working dir is set in yaml header
```

Install packages and set working dir  
```{r, cache = TRUE, tidy = TRUE, lazy = TRUE, results="hide"}
# install pcks
packages <- c("stringr")   
if (require(packages)) {
  install.packages(packages,dependencies = T)
  require(packages)
}
lapply(packages,library,character.only=T)
```

###   

## Problems  

### DNA	Counting DNA Nucleotides	  
```{r}
s <- read.csv("rosalind_dna.txt",header=F,sep=",",stringsAsFactors = F);s
str_count(s,c("A","C","G","T"))
```

### RNA	Transcribing DNA into RNA  
```{r}

```

